{"name": "测试登录", "status": "broken", "statusDetails": {"message": "AttributeError: 'AssertUtil' object has no attribute 'log'", "trace": "self = <utils.AssertUtil.AssertUtil object at 0x104805df0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n>           assert expected_body in body\nE           AssertionError\n\n../utils/AssertUtil.py:52: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"测试登录\")\n    @allure.description(\"执行测试登录的结果是test\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login():\n        # 3、定义测试数据\n        conf_y = ConfigYaml()\n        url_path = conf_y.get_conf_url()\n        url = url_path + \"/sys/login\"\n        # url = \"http://ihrm-java.itheima.net/api/sys/login\"\n        data = {\"mobile\": \"13800000002\", \"password\": \"888itcast.CN764%.\"}\n        headers = {\"Content-Type\": \"application/json\"}\n        # 4、发送POST请求\n        # r = requests.post(url, json=data, headers=headers)\n        # r = requests_post(url, json=data, headers=headers)\n        request = Request()\n        r = request.post(url, json=data, headers=headers)\n        # 5、输出结果\n        # print(r.json())\n        print(r)\n        # 验证\n        # 返回状态码\n        code = r[\"code\"]\n        AssertUtil().assert_code(code, 200)\n        # 返回body\n        # body = json.dumps(r[\"body\"])\n        # assert '\"success\": true,\"data\": \"9829dd98-6dcc-41e1-901d-4e434cde36d6\"' in body\n        body = r[\"body\"]\n>       AssertUtil().assert_in_body(body, '\"success\": true')\n\ntest_Login.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.AssertUtil.AssertUtil object at 0x104805df0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n            assert expected_body in body\n            return True\n        except:\n>           self.log.error(\"不包含或者body错误,body is %s,expected_body is %s\" % (body, expected_body))\nE           AttributeError: 'AssertUtil' object has no attribute 'log'\n\n../utils/AssertUtil.py:55: AttributeError"}, "description": "执行测试登录的结果是test", "attachments": [{"name": "log", "source": "3dd58b16-a282-470e-8012-9b6de03a16f8-attachment.txt", "type": "text/plain"}], "start": 1695390758982, "stop": 1695390759109, "uuid": "3b4a7288-19aa-4686-aa9b-a57bef059068", "historyId": "e74e289d6115a7155493cea255fe26cd", "testCaseId": "e74e289d6115a7155493cea255fe26cd", "fullName": "testcase.test_Login#test_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_Login"}, {"name": "host", "value": "lifaliangdeMacBook-Air.local"}, {"name": "thread", "value": "33748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_Login"}]}